receivers:
  filelog:
    include: [ /usr/src/app/*.log ]
    operators:
    - type: json_parser
      timestamp:
        parse_from: attributes.asctime
        layout: '%Y-%m-%dT%H:%M:%S'
      severity:
        parse_from: attributes.levelname
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [ filelog ]
      exporters: [ logging ]
